[package]
name = "tokio-quiche"
version = "0.2.0"
authors = ["quininer <quininer@live.com>", "cauvmou <cauvmou.8855@gmail.com>"]
edition = "2021"

[dependencies]
log = "^0.4"
rand = "^0.8"
ring = "^0.16.20"
smallvec = "^1.10"
tokio = { version = "1", features = ["full"] }
tokio-timer = "^0.2.13"
quiche = "^0.16.0"
pollster = "^0.3.0"
rust-crypto = "^0.2"
chrono = "^0.4.23"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
simple_logger = "*"